samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132402.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132402.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132403.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132403.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132404.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132404.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132405.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132405.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132406.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132406.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132407.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132407.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132408.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132408.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132409.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132409.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132410.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132410.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132411.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132411.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132412.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132412.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132413.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132413.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132414.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132414.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132415.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132415.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132416.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132416.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132417.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132417.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132418.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132418.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132419.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132419.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132420.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132420.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132421.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132421.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132422.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132422.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132423.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132423.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132424.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132424.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132425.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132425.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132426.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132426.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132427.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132427.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132428.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132428.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132429.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132429.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132430.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132430.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132431.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132431.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132432.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132432.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132433.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132433.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132434.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132434.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132435.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132435.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132436.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132436.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132437.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132437.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132438.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132438.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132439.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132439.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132440.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132440.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132441.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132441.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132442.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132442.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132443.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132443.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132444.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132444.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132445.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132445.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132446.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132446.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132447.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132447.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132448.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132448.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132449.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132449.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132450.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132450.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132451.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132451.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132452.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132452.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132453.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132453.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132454.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132454.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132455.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132455.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132456.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132456.bed
samtools view -bq 10 ../runs/sorted_bamFiles/SRR2132457.bam | bedtools coverage -a /scratch/gslab/mpandey/lib/updated_IntronCoord.bed -b stdin -F 0.10 -split > ../runs/IntronCoverage/SRR2132457.bed
